joint_kp: [
  200, 200, 200,
  200, 200, 200,
  200, 200, 200,
  200, 200, 200,
]

joint_kd: [
  5, 5, 5,
  5, 5, 5,
  5, 5, 5,
  5, 5, 5,
]

def_joint_pos: [
  0, 0.7854, -1.5707,
  0, 0.7854, -1.5707,
  0, 0.7854, -1.5707,
  0, 0.7854, -1.5707,
]