def_joint_pos: [
  0, 0.7854, -1.5708,
  0, 0.7854, -1.5708,
  0, 0.7854, -1.5708,
  0, 0.7854, -1.5708,
]

nominal_joint_kp: [
  200, 200, 200,
  200, 200, 200,
  200, 200, 200,
  200, 200, 200,
]

nominal_joint_kd: [
  5, 5, 5,
  5, 5, 5,
  5, 5, 5,
  5, 5, 5,
]

damping_kd: [
  10, 10, 10,
  10, 10, 10,
  10, 10, 10,
  10, 10, 10,
]